### ISSUE TITLE
RFC: Add card variants to data

### ISSUE THREAD

**Issue by mattoni** [PokemonTCG/pokemon-tcg-data#276]
Hello!

I'd like to start the discussion on how to incorporate different card variants into this data set.

Our friends over at tcgcollector.com have done [extensive work ](https://tcgcollector.gitlab.io/documents/card-database/conventions/) in cataloguing the various variants, and as I understand it will be releasing a full list soon. This may be a good source. Another decent source is TcgPlayer - they have pricing for most variants of the international sets.

It's important to consider the following when modeling out how the data should be stored here:

- Cards can have multiple variants
- Support for images for particular variants
- Pricing for variants

With that in mind, I propose that we add a new set of JSON files-one for international and one for japanese - that has an array of variant names available for each. We could use the names as the identifier:

```json
["First Edition", "First Edition (Shadowless)", "Normal", ....]
```

And on each card, add the ones that are relevant to that card. We could add a "variants" section to the images, that is a map of name -> url to have specific images for each variant, and do the same in pricing. 

```json
 {
    "id": "base3-5",
    "name": "Gengar",
     ...
     "variants": ["First Edition", "Normal"],
     "images": {
        // Implied "Normal" variant for backward compatibility
        "small": "https://images.pokemontcg.io/base3/5.png",
        "large": "https://images.pokemontcg.io/base3/5_hires.png",
        "variants": {
           "First Edition": {
               "small": "https://images.pokemontcg.io/base3/5.png",
               "large": "https://images.pokemontcg.io/base3/5_hires.png",
           }
           ....
        }
      }
}
```

It would obviously be a bit of work to identify and add variants, but this is a huge part of what the TCG is. If added, this would significantly enrich the API.

**Comment by mattoni** [comment]
@adback03 Checking back in on this to see if there is any interest here. It'd be awesome to get the foundation established so we can begin documenting variants.

**Comment by b3nk3lly** [comment]
I would also like to see this ! Another good source of variants could be https://dextcg.com/. 

We would need to decide on a naming convention since there are differences in the variant names between this site and others like https://www.tcgcollector.com/. For example, see this Iron Moth card from Paradox Rift [on DexTCG](https://app.dextcg.com/cards/sv4-28) and [on TCG Collector](https://www.tcgcollector.com/cards/43029/iron-moth-paradox-rift-028-182). DexTCG uses variant names "Holo", "Normal", and "Set Stamp", while TCG Collector uses names like "Normal Holo", "Non-holo", and "Paradox Rift Stamp". 

There's a discussion to be had about what the "normal" variant means for a card that is holo by default. Same goes for how to classify variants with the set stamp: do we use a generic name like "Set Stamp", or a unique one for each set like "Paradox Rift Stamp" ?

**Comment by mattoni** [comment]
Yes, still want to see this. I think it'd be best to start anywhere and just get the data out there and correct it over time to be honest. I've started working on a "companion" API that focuses explicitly on variants to be used with the ids here since there hasn't been much movement on it and it's a pretty big part of the TCG. I'll work on the data structure a bit more then put it out there and see if people have ideas.

**Comment by adback03** [comment]
Variants will be part of the new API which is currently in beta. They are supported for all english (and japanese) sets. I don't plan on adding variant data to this API. The variant data of my new api will also have pricing per variant. As of now, the variants will be an array of objects that have the variant name, images array (if we have good pics for the variant), and prices.

If you'd like more info about this and what the new API is looking like, feel free to DM me. I'm still working on a public launch date, but I'm hoping to do so before the end of the year.
