### ISSUE TITLE
Aquapolis Holo Numbering

### ISSUE THREAD

**Issue by mmxxiii** [PokemonTCG/pokemon-tcg-data#29]
RE: https://github.com/PokemonTCG/pokemon-tcg-api/issues/74

I'd be happy to push an update for this issue, but I wanted to make sure that changing them to non numeric values won't break anything in the API.

@adback03: Is there any problem with either the card ID or card Number being changed to non-numeric values (e.g. `"number": "182"` becomes `"number": "H32"`, and `"id": "ecard2-182"` becomes "id": `"ecard2-H2"`)?

**Comment by adback03** [comment]
In terms of this API and consuming apps (like sdks), it would be non-breaking. I can't guarantee that users aren't using that ID as their own identifier though. I'd try posting this issue to the discord channel and see if anyone would have a problem with changing those IDs.

Otherwise, we'd have to leave the ID field the same, but could still change the number field.

**Comment by axpendix** [comment]
Should not break anything. There are many non-numeric number fields in other sets such as Unseen Forces.
